site_name: Pokemerald

theme:
  name: readthedocs

nav:
  - Home: index.md
  - Pokedex: pokedex.md
  - Towns and Routes: towns-and-routes.md
  - Move Changes: moves.md
  - Other Changes: other-changes.md

extra_css:
  - stylesheets/extra.css

watch:
  - docs
