#ifndef GUARD_CONSTANTS_WILD_ENCOUNTER_H
#define GUARD_CONSTANTS_WILD_ENCOUNTER_H

#define LAND_WILD_COUNT     12
#define WATER_WILD_COUNT    5
#define ROCK_WILD_COUNT     5
#define FISH_WILD_COUNT     10

#define NUM_ALTERING_CAVE_TABLES 9

#define TIME_OF_DAY_MORNING  0  // 5am - 10am
#define TIME_OF_DAY_DAY      1  // 10am - 5pm
#define TIME_OF_DAY_EVENING  2  // 5pm - 10pm
#define TIME_OF_DAY_NIGHT    3  // 10pm - 5am

#endif // GUARD_CONSTANTS_WILD_ENCOUNTER_H
